spring.datasource:
  url:                  jdbc:mysql://localhost:3306/task_db?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Moscow&useSSL=false
  username:             root
  password:             test#12test
  #initialization-mode:  never    #always

spring.jpa:
  hibernate.ddl-auto:   create #update

server.servlet:
  session.timeout:      10m